### ISSUE TITLE
400 Bad Request , Docker Install

### ISSUE THREAD

**Issue by osamahamad** [offensive-hub/black-widow#8]
Getting 400 Bad Request when trying to install through docker , 

```
docker run -d -p 8095:80 offensive/black-widow -g
```

When trying to load on port 8095.

![image](https://user-images.githubusercontent.com/59566963/86031049-03a36500-ba3e-11ea-93ca-d4e8755f213d.png)

I'm running Ubuntu 18.04  .
Docker version 19.03.6, build 369ce74a3c

**Comment by FabrizioFubelli** [comment]
Hello Osama,

I cannot replace your issue.
Have you tried another port by running, for example, the following command ?

`docker run -d -p 8195:80 offensive/black-widow -g`

**Comment by osamahamad** [comment]
Hi , 

Yes i tried this with a list of solutions comes into my mind . 
It didn't work out like for example : 8195 port when opening also gives the same error message.

**Comment by FabrizioFubelli** [comment]
@osamahamad please can try the following steps:

1. Start Docker with: `docker run -d -p 8095:80 offensive/black-widow -g`
2. Run the command: `docker exec -ti <container_id> sh`
3. Now you are inside Docker. DON'T move out from your current directory.
4. Enable **debug** by running: `sed -i 's/APP_DEBUG=False/APP_DEBUG=True/g' ./black_widow/.env`
5. Run `killall gunicorn`
6. Now the Docker is stopped because the main process has been killed
7. Run `docker start <container_id>`
8. Run `docker exec -ti <container_id> sh`
9. Execute inside Docker `tail -f /tmp/black-widow/black-widow.log`
10. Visit [**http://127.0.0.1:8095**](http://127.0.0.1:8095) and look at the log file thanks to previous command
